Update main.tf
There appears to be an error where node is using compiler nic instead of its own

Failed on localhost:

  Error: Invalid index

    on modules\instances\main.tf line 347, in resource "azurerm_linux_virtual_machine" "node":
   347:     internalDNS = var.domain_name == null ? "pe-node-${count.index}-${var.id}.${azurerm_network_interface.compiler_nic[count.index].internal_domain_name_suffix}" : "pe-node-${count.index}-${var.id}.${var.domain_name}"
      Ôö£ÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇ
      Ôöé azurerm_network_interface.compiler_nic is empty tuple
      Ôöé count.index is 0

  The given key does not identify an element in this collection value: the
  collection has no elements.
Failed on 1 target: localhost